server:
  port: 8081

spring:
  application:
    name: demo-service-provider
  zipkin:
    base-url: http://localhost:8085
  sleuth:
    sampler:
      percentage: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
