server:
  port: 8086

spring:
  application:
    name: demo-service-config
  profiles:
    active: native # for reading local file config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
